import { createHash, generateKeyPairSync } from 'node:crypto';
import { toBase32 } from '../utils/base32';

/**
 * Ed25519 I2P destination + privKey generation.
 *
 * Wire compatibility with the Android side (Java net.i2p.data.Destination)
 * is a hard requirement — a destination file generated by this module must
 * produce a b32Address that the Java side also produces from the same
 * private key material. Both implementations agree on:
 *
 *  1. Destination blob layout (matches net.i2p.data.Destination):
 *       [PublicKey 32B][SigningPublicKey 32B][Certificate]
 *     where the Certificate here is the 1-byte NULL certificate (0x00,
 *     type=KEYCERT_NULL). For EdDSA-Ed25519 SigningPublicKey == PublicKey
 *     (single-key variant per I2P spec) — the 32+32 redundancy is
 *     intentional, not a duplication bug.
 *
 *  2. privKey blob layout (matches net.i2p.data.PrivateKey file):
 *       [PrivateKey 32B][PublicKey 32B][padding to 384 bytes total]
 *     The first 64 bytes are the real keypair; the trailing 320 bytes are
 *     zeros so the blob is exactly 384 bytes, matching Java's I2PClient
 *     output. This is what IdentityStore.round-trips on disk.
 *
 *  3. b32Address = base32(SHA-256(destination)) + ".b32.i2p", where the
 *     base32 alphabet is RFC 4648 lowercase (a-z, 2-7) — identical to I2P's
 *     own b32 alphabet. The 32-byte SHA-256 digest encodes to exactly 52
 *     base32 chars (256 bits / 5 = 51.2 → 52 chars); no truncation needed.
 *
 * References:
 *   - https://geti2p.net/spec/destination
 *   - https://geti2p.net/spec/b32
 *   - https://geti2p.net/spec/encryption#elgamal-vs-ecies (Ed25519 variant)
 */

const PUBLIC_KEY_LENGTH = 32;
/** Ed25519 raw public key. */
const PRIVATE_KEY_LENGTH = 32;
/** Ed25519 raw private key seed. */
const CERT_NULL_LENGTH = 1;
/** NULL certificate = 1 byte 0x00 (KEYCERT_NULL). */
const CERT_NULL_BYTE = 0x00;
const DESTINATION_LENGTH = PUBLIC_KEY_LENGTH * 2 + CERT_NULL_LENGTH; // 65 bytes
const PRIVKEY_BLOB_LENGTH = 384; // 32 priv + 32 pub + 320 padding

/**
 * I2P Ed25519 destination produced by `generateEd25519Destination`.
 *
 * - `privKey`: 384-byte blob suitable for IdentityStore.save(). Layout:
 *   [privKey 32B][pubKey 32B][zeros 320B].
 * - `publicKey`: 32-byte Ed25519 public key (encryption key in I2P).
 * - `signingPublicKey`: 32-byte Ed25519 signing key. For Ed25519 this equals
 *   `publicKey` (single-key variant).
 * - `b32Address`: SHA-256(destination) base32-encoded + ".b32.i2p".
 */
export interface GeneratedDestination {
  privKey: Uint8Array;
  publicKey: Uint8Array;
  signingPublicKey: Uint8Array;
  b32Address: string;
}

/**
 * Generate a fresh Ed25519 I2P destination. The resulting `privKey` blob
 * is compatible with IdentityStore.save() and round-trips on disk.
 */
export async function generateEd25519Destination(): Promise<GeneratedDestination> {
  const { publicKey, privateKey } = generateKeyPairSync('ed25519');

  // Node's KeyObject exports for `ed25519` are:
  //   - publicKey SPKI:  12-byte algorithm header + 32 raw bytes
  //   - privateKey PKCS8: 16-byte algorithm header + 32 raw seed bytes
  // The trailing 32 bytes are the raw Ed25519 key material we want.
  const pubKeyBytes = new Uint8Array(
    publicKey.export({ format: 'der', type: 'spki' }).subarray(-PUBLIC_KEY_LENGTH),
  );
  const privKeyBytes = new Uint8Array(
    privateKey.export({ format: 'der', type: 'pkcs8' }).subarray(-PRIVATE_KEY_LENGTH),
  );

  const destination = buildDestinationBlob(pubKeyBytes);
  const privBlob = buildPrivKeyBlob(privKeyBytes, pubKeyBytes);
  const b32Address = await computeB32FromDestination(destination);

  return {
    privKey: privBlob,
    publicKey: pubKeyBytes,
    signingPublicKey: pubKeyBytes,
    b32Address,
  };
}

/**
 * Compute the b32Address from a 384-byte privKey blob (the same format
 * IdentityStore yields on load). This is the reverse-engineering path that
 * lets callers rebuild a b32 for an existing identity without re-deriving
 * the destination from raw key bytes.
 *
 * Algorithm: extract public key at bytes 32..63, rebuild the 65-byte
 * destination blob, SHA-256 it, base32-encode (lowercase), append ".b32.i2p".
 *
 * Throws if `privKey` is not 384 bytes (the only valid I2P-Ed25519 size).
 */
export async function computeB32FromPrivKey(privKey: Uint8Array): Promise<string> {
  if (privKey.length !== PRIVKEY_BLOB_LENGTH) {
    throw new Error(
      `computeB32FromPrivKey: expected 384-byte privKey blob, got ${privKey.length}`,
    );
  }
  const pubKeyBytes = privKey.subarray(PUBLIC_KEY_LENGTH, PUBLIC_KEY_LENGTH * 2);
  // Defensive copy: `subarray` is a view, callers could mutate the source.
  const destination = buildDestinationBlob(new Uint8Array(pubKeyBytes));
  return computeB32FromDestination(destination);
}

/**
 * Internal: assemble the 65-byte destination blob (pubKey || signingPubKey
 * || cert). For Ed25519 signingPubKey === pubKey (single-key) — the
 * duplication is intentional per I2P spec.
 */
function buildDestinationBlob(pubKeyBytes: Uint8Array): Uint8Array {
  if (pubKeyBytes.length !== PUBLIC_KEY_LENGTH) {
    throw new Error(
      `buildDestinationBlob: expected 32-byte public key, got ${pubKeyBytes.length}`,
    );
  }
  const dest = new Uint8Array(DESTINATION_LENGTH);
  dest.set(pubKeyBytes, 0);
  dest.set(pubKeyBytes, PUBLIC_KEY_LENGTH); // EdDSA uses same key for both
  dest.set([CERT_NULL_BYTE], PUBLIC_KEY_LENGTH * 2);
  return dest;
}

/**
 * Internal: assemble the 384-byte privKey blob. Public key goes at offset
 * 32 (NOT a duplicate of the private key — the brief's draft put the
 * private key at offset 32, which is wrong and would break I2P logs).
 */
function buildPrivKeyBlob(privKeyBytes: Uint8Array, pubKeyBytes: Uint8Array): Uint8Array {
  if (privKeyBytes.length !== PRIVATE_KEY_LENGTH) {
    throw new Error(
      `buildPrivKeyBlob: expected 32-byte private key, got ${privKeyBytes.length}`,
    );
  }
  if (pubKeyBytes.length !== PUBLIC_KEY_LENGTH) {
    throw new Error(
      `buildPrivKeyBlob: expected 32-byte public key, got ${pubKeyBytes.length}`,
    );
  }
  const blob = new Uint8Array(PRIVKEY_BLOB_LENGTH);
  blob.set(privKeyBytes, 0);
  blob.set(pubKeyBytes, PRIVATE_KEY_LENGTH);
  // Trailing 320 bytes stay zero.
  return blob;
}

/**
 * Internal: SHA-256(destination) → lowercase base32 (52 chars) + ".b32.i2p".
 */
async function computeB32FromDestination(destination: Uint8Array): Promise<string> {
  const digest = createHash('sha256').update(destination).digest();
  // 32 bytes = 256 bits → 52 base32 chars (256 / 5 = 51.2, rounded up).
  // The trailing 4 bits are padding and not visible in the encoded output.
  const b32 = toBase32(new Uint8Array(digest));
  return `${b32}.b32.i2p`;
}
